'use strict';

const path = require('node:path');
const { asArray, slugify, truncate, unique } = require('./util');
const { stringifyFrontmatter } = require('./frontmatter');

const CAPABILITY_ALIASES = new Map([
  ['read', 'read'], ['notebookread', 'read'], ['view', 'read'], ['cat', 'read'], ['readfile', 'read'],
  ['write', 'edit'], ['edit', 'edit'], ['multiedit', 'edit'], ['notebookedit', 'edit'], ['applypatch', 'edit'], ['patch', 'edit'], ['writefile', 'edit'],
  ['bash', 'execute'], ['shell', 'execute'], ['execute', 'execute'], ['terminal', 'execute'], ['powershell', 'execute'], ['shell_exec', 'execute'],
  ['grep', 'search'], ['glob', 'search'], ['ls', 'search'], ['search', 'search'], ['lsp', 'search'], ['find', 'search'],
  ['websearch', 'web'], ['webfetch', 'web'], ['web', 'web'], ['browser', 'web'], ['fetch', 'web'],
  ['task', 'delegate'], ['agent', 'delegate'], ['delegatetask', 'delegate'], ['subagent', 'delegate'],
  ['todowrite', 'todo'], ['todo', 'todo'], ['manage_todo_list', 'todo'],
  ['skill', 'skill'], ['skillview', 'skill'], ['skill_view', 'skill'],
  ['mcp', 'mcp'],
]);

const CAPABILITY_ORDER = ['read', 'edit', 'execute', 'search', 'web', 'delegate', 'todo', 'skill', 'mcp'];

function normalizedToolKey(value) {
  return String(value || '').replace(/[^A-Za-z0-9_]/g, '').toLowerCase();
}

function normalizeTools(value, specified = value !== undefined && value !== null) {
  const rawInput = asArray(value).flatMap((item) => typeof item === 'string' ? item.split(',') : [item]);
  const raw = unique(rawInput.map((item) => String(item).trim()).filter(Boolean));
  const capabilities = [];
  const unknown = [];
  for (const item of raw) {
    const key = normalizedToolKey(item);
    const capability = CAPABILITY_ALIASES.get(key);
    if (capability) capabilities.push(capability);
    else unknown.push(item);
  }
  return {
    specified,
    raw,
    capabilities: unique(capabilities).sort((a, b) => CAPABILITY_ORDER.indexOf(a) - CAPABILITY_ORDER.indexOf(b)),
    unknown: unique(unknown),
  };
}

function sourceTools(entity) {
  const data = entity.data || {};
  const keys = ['tools', 'allowed-tools', 'allowedTools'];
  const key = keys.find((candidate) => Object.prototype.hasOwnProperty.call(data, candidate));
  return key ? normalizeTools(data[key], true) : normalizeTools(undefined, false);
}

function normalizeDescription(value, fallback) {
  const text = String(value || fallback || '').replace(/\s+/g, ' ').trim();
  return truncate(text || 'Reusable agent capability generated by BuildWithCLI.', 1024);
}

function cleanMetadata(value) {
  const output = {};
  if (value && typeof value === 'object' && !Array.isArray(value)) {
    for (const [key, item] of Object.entries(value)) {
      if (item == null || typeof item === 'object') continue;
      output[String(key)] = String(item);
    }
  }
  return output;
}

function standardSkillData(entity, target, extra = {}) {
  const original = entity.data || {};
  const metadata = {
    ...cleanMetadata(original.metadata),
    'buildwithcli-source': entity.sourcePath,
    'buildwithcli-kind': entity.kind,
    'buildwithcli-target': target,
  };
  if (entity.originalName && entity.originalName !== entity.name) metadata['buildwithcli-original-name'] = entity.originalName;
  if (original.category) metadata.category = String(original.category);
  if (entity.namespace) metadata.namespace = entity.namespace;

  const data = {
    name: entity.name,
    description: normalizeDescription(original.description, `${entity.name} ${entity.kind}`),
  };
  if (original.license) data.license = String(original.license);
  data.compatibility = truncate(original.compatibility || `Generated for ${target} by BuildWithCLI`, 500);
  if (Object.keys(metadata).length) data.metadata = metadata;
  const tools = sourceTools(entity);
  if (tools.specified) data['allowed-tools'] = original['allowed-tools'] ?? original.allowedTools ?? original.tools ?? '';
  for (const [key, value] of Object.entries(extra)) {
    if (value !== undefined) data[key] = value;
  }
  return data;
}

function renderSkill(entity, target, options = {}) {
  let body = entity.body || '';
  const prefix = options.prefix || '';
  if (prefix) body = `${prefix.trim()}\n\n${body.replace(/^\s+/, '')}`;
  return stringifyFrontmatter(standardSkillData(entity, target, options.frontmatter || {}), body);
}

function skillFromAgent(entity, target, options = {}) {
  const name = options.name || slugify(`agent-${entity.name}`);
  const converted = {
    ...entity,
    name,
    originalName: entity.name,
    kind: 'agent-skill',
    data: {
      ...entity.data,
      name,
      description: normalizeDescription(entity.description, `Use the ${entity.name} specialist workflow`),
    },
  };
  const prefix = [
    `# ${entity.name} specialist`,
    '',
    'Use this skill when the task matches this specialist. Follow the original agent instructions below as the operating contract.',
  ].join('\n');
  return { name, content: renderSkill(converted, target, { prefix, frontmatter: options.frontmatter }) };
}

function commandArgumentHint(entity) {
  return String(entity.data?.['argument-hint'] ?? entity.data?.argumentHint ?? entity.data?.argument_hint ?? '<arguments>');
}

function skillFromCommand(entity, target, options = {}) {
  const name = options.name || slugify(`command-${entity.name}`);
  const converted = {
    ...entity,
    name,
    originalName: entity.name,
    kind: 'command-skill',
    data: {
      ...entity.data,
      name,
      description: normalizeDescription(entity.description, `Run the ${entity.name} workflow`),
    },
  };
  const hint = commandArgumentHint(entity);
  const prefix = [
    `# /${entity.name} workflow`,
    '',
    `Expected arguments: ${hint}`,
    '',
    'Treat the user text following the invocation as `$ARGUMENTS`. Execute the workflow below and verify the result.',
  ].join('\n');
  const frontmatter = { ...(options.frontmatter || {}) };
  if (options.includeInvocationFields) {
    frontmatter['argument-hint'] = hint;
    frontmatter['user-invocable'] = true;
  }
  return { name, content: renderSkill(converted, target, { prefix, frontmatter }) };
}

function namespaceForPath(relativePath) {
  const parts = String(relativePath).replace(/\\/g, '/').split('/');
  const pluginIndex = parts.indexOf('plugins');
  if (pluginIndex >= 0 && parts[pluginIndex + 1]) return slugify(parts[pluginIndex + 1]);
  return slugify(path.basename(path.dirname(relativePath)), 'root');
}

const HOOK_EVENT_MAP = {
  claude: {
    PreToolUse: 'PreToolUse', PostToolUse: 'PostToolUse', Stop: 'Stop', Notification: 'Notification',
    SessionStart: 'SessionStart', SessionEnd: 'SessionEnd', UserPromptSubmit: 'UserPromptSubmit',
    PreCompact: 'PreCompact', PostCompact: 'PostCompact', SubagentStop: 'SubagentStop', SubagentStart: 'SubagentStart',
    PermissionRequest: 'PermissionRequest',
  },
  copilot: {
    PreToolUse: 'preToolUse', PostToolUse: 'postToolUse', Stop: 'agentStop', Notification: 'notification',
    SessionStart: 'sessionStart', SessionEnd: 'sessionEnd', UserPromptSubmit: 'userPromptSubmitted',
    PreCompact: 'preCompact', PostCompact: 'postCompact', SubagentStop: 'subagentStop', SubagentStart: 'subagentStart',
    PermissionRequest: 'permissionRequest',
  },
  codex: {
    PreToolUse: 'PreToolUse', PostToolUse: 'PostToolUse', Stop: 'Stop', SessionStart: 'SessionStart',
    SessionEnd: 'SessionEnd', UserPromptSubmit: 'UserPromptSubmit', PreCompact: 'PreCompact', PostCompact: 'PostCompact',
    SubagentStop: 'SubagentStop', SubagentStart: 'SubagentStart', PermissionRequest: 'PermissionRequest',
  },
  hermes: {
    PreToolUse: 'pre_tool_call', PostToolUse: 'post_tool_call', Stop: 'on_session_end',
    SessionStart: 'on_session_start', SessionEnd: 'on_session_finalize', SubagentStop: 'subagent_stop',
    SubagentStart: 'subagent_start', UserPromptSubmit: 'pre_llm_call',
  },
  opencode: {
    PreToolUse: 'tool.execute.before', PostToolUse: 'tool.execute.after', Stop: 'session.idle',
    SessionStart: 'session.created', SessionEnd: 'session.deleted', PreCompact: 'session.compacted',
    Notification: 'notification',
  },
};

function canonicalHookEvent(value) {
  const raw = String(value || '').trim();
  const normalized = raw.replace(/[_-]/g, '').toLowerCase();
  const aliases = {
    pretooluse: 'PreToolUse', posttooluse: 'PostToolUse', stop: 'Stop', agentstop: 'Stop',
    notification: 'Notification', sessionstart: 'SessionStart', sessionend: 'SessionEnd',
    userpromptsubmit: 'UserPromptSubmit', userpromptsubmitted: 'UserPromptSubmit',
    precompact: 'PreCompact', postcompact: 'PostCompact', subagentstop: 'SubagentStop',
    subagentstart: 'SubagentStart', permissionrequest: 'PermissionRequest',
    pretoolcall: 'PreToolUse', posttoolcall: 'PostToolUse', onsessionstart: 'SessionStart',
    onsessionend: 'SessionEnd', onsessionfinalize: 'SessionEnd', prellmcall: 'UserPromptSubmit',
  };
  return aliases[normalized] || raw;
}

function mapHookEvent(event, target) {
  return HOOK_EVENT_MAP[target]?.[canonicalHookEvent(event)] || null;
}

function normalizeMatcher(value) {
  const raw = String(value ?? '*').trim() || '*';
  if (raw.length > 256) return { supported: false, raw, patterns: [] };
  const parts = raw.split('|').map((item) => item.trim()).filter(Boolean);
  if (!parts.length || parts.some((item) => /[^A-Za-z0-9_.:/@*? -]/.test(item))) {
    return { supported: false, raw, patterns: [] };
  }
  return { supported: true, raw, patterns: unique(parts) };
}

module.exports = {
  CAPABILITY_ALIASES,
  CAPABILITY_ORDER,
  HOOK_EVENT_MAP,
  canonicalHookEvent,
  commandArgumentHint,
  mapHookEvent,
  namespaceForPath,
  normalizeDescription,
  normalizeMatcher,
  normalizeTools,
  normalizedToolKey,
  renderSkill,
  skillFromAgent,
  skillFromCommand,
  sourceTools,
  standardSkillData,
};
